version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8866
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8866
    env_file:
      - ./.env
    # network_mode: "host"        
    restart: always
    depends_on:
      - db
  db:
    # network_mode: "host"        
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=zones
      - POSTGRES_PASSWORD=zones
      - POSTGRES_DB=zones

volumes:
  postgres_data:
