# Generated by Django 4.1.4 on 2022-12-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="zone",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agencies",
                to="zones.zone",
            ),
        ),
    ]
