# Generated by Django 4.1.4 on 2022-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0003_alter_agency_options_alter_zone_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="agency_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="zone",
            name="zone_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
