# Generated by Django 4.1.4 on 2022-12-09 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0004_alter_agency_agency_name_alter_zone_zone_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technician_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ("technician_name",),
            },
        ),
        migrations.AddField(
            model_name="zone",
            name="technician",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zones.technician",
            ),
        ),
    ]
