# Generated by Django 4.1.4 on 2022-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0005_technician_zone_technician"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zone",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="zone",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
